### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by theusaf** [Czaplicki/mcfunction#4]
[Enter steps to reproduce:]

1. Begin typing out a mcfunction command.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.2
**Thrown From**: [mcfunction-support](https://github.com/Czaplicki/mcfunction-support) package 3.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/tisomadmin/.atom/packages/mcfunction-support/lib/provider.js:292

TypeError: Cannot read property 'startsWith' of undefined
    at Object.getCommandOption (/packages/mcfunction-support/lib/provider.js:292:19)
    at Object.getSuggestions (/packages/mcfunction-support/lib/provider.js:160:46)
    at o.forEach.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:647224)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:646740)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:646478)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:655011)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656102)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504418)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492523)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:258055)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:94325)
```

### Commands

```
     -3:57.8.0 editor:consolidate-selections (input.hidden-input)
     -3:57.8.0 core:cancel (input.hidden-input)
     -3:56.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  2x -3:55.4.0 core:move-down (input.hidden-input)
     -3:55 core:confirm (input.hidden-input)
  2x -3:53.8.0 core:move-down (input.hidden-input)
     -3:52.5.0 core:backspace (input.hidden-input)
     -3:52 autocomplete-plus:cancel (input.hidden-input)
     -3:51.6.0 core:move-down (input.hidden-input)
  2x -3:50.4.0 core:backspace (input.hidden-input)
  3x -3:48.4.0 autocomplete-plus:confirm (input.hidden-input)
     -3:41.8.0 core:backspace (input.hidden-input)
     -3:40.3.0 editor:newline (input.hidden-input)
     -0:04.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:move-down (input.hidden-input)
     -0:02.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-java-decompiler 0.1.2 
audio 1.5.7 
language-markdown 0.37.0 
mcfunction-lang 1.16.0-20w12a 
mcfunction-support 3.6.0 
sort-lines 0.19.0 
svg-preview 0.14.0 
teletype 0.13.4 
```
---
Previously discussed in https://github.com/Czaplicki/mcfunction-support-resources/issues/4. Same problem with res.json.

**Comment by ChrizziCarrot** [comment]
This issue still exists. Is there a fix coming soon?
![Screenshot_280](https://user-images.githubusercontent.com/62596382/77418794-b1f89800-6dc7-11ea-8920-d98b8d42975b.png)

**Comment by theusaf** [comment]
I don't know if he will update this package soon, as his README says that he stopped using atom. You may want to check out other mcfunction packages, like the original one or mcfunction-lang.

**Comment by zandercodes** [comment]
Same problem

**Comment by its-brody** [comment]
I type execute then I get a ton of spam errors on the side...

**Comment by ghost** [comment]
Why came this error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: LAPTOP-PV49KKHA
**Thrown From**: [mcfunction-support](https://github.com/Czaplicki/mcfunction-support) package 3.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At C:\Users\Simon\.atom\packages\mcfunction-support\lib\provider.js:292

TypeError: Cannot read property 'startsWith' of undefined
    at Object.getCommandOption (/packages/mcfunction-support/lib/provider.js:292:19)
    at Object.getSuggestions (/packages/mcfunction-support/lib/provider.js:175:16)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:648842
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:648358)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:648096)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:656629)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:657720)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1202901)
    at TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:505021)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:493176)
    at TextEditor.transact (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:24215)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:16150
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:258561)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:94346)
```

### Commands

```
  7x -1:38.3.0 core:backspace (input.hidden-input)
     -1:33.5.0 core:move-down (input.hidden-input)
     -1:32.7.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:21.6.0 core:backspace (input.hidden-input)
  7x -1:17 core:move-left (input.hidden-input)
     -1:15.5.0 core:move-right (input.hidden-input)
     -1:15.1.0 core:move-left (input.hidden-input)
     -1:14.7.0 core:backspace (input.hidden-input)
  3x -1:14.4.0 core:move-right (input.hidden-input)
  3x -1:13.7.0 core:move-left (input.hidden-input)
  7x -1:11.5.0 core:move-right (input.hidden-input)
     -1:05.9.0 autocomplete-plus:confirm (input.hidden-input)
  6x -1:04.6.0 core:backspace (input.hidden-input)
     -0:25.6.0 core:move-left (input.hidden-input)
  3x -0:25.4.0 core:move-right (input.hidden-input)
     -0:20.1.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
mcfunction-support 3.6.0 
```

**Comment by MeneerMathieu** [comment]
I found a fix. Go to your Users\USER\.atom\packages folder and delete the package. It still exist in your Users\User\Local\atom\packages folder and I don't know how, but everything works after you deleted the first folder.
